# Generated by Django 5.2.4 on 2025-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phishing', 'Ֆիշինգ'), ('malware', 'Վնասակար ծրագիր'), ('ddos', 'DDoS հարձակում'), ('other', 'Այլ')], max_length=20, verbose_name='Տեսակ')),
                ('source_country', models.CharField(blank=True, max_length=100, verbose_name='Աղբյուրի երկիր')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Հայտնաբերման ժամանակ')),
                ('description', models.TextField(blank=True, verbose_name='Նկարագրություն')),
            ],
            options={
                'verbose_name': 'Սպառնալիք',
                'verbose_name_plural': 'Սպառնալիքներ',
            },
        ),
    ]
