# Generated by Django 5.2.4 on 2025-07-23 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_phishingreport_platform_source_contactguideline'),
        ('threat_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(max_length=50, verbose_name='Սպառնալիքի տեսակ')),
                ('source_country', models.CharField(max_length=100, verbose_name='Աղբյուրի երկիր')),
                ('target_sector', models.CharField(blank=True, max_length=100, verbose_name='Թիրախային ոլորտ')),
                ('description', models.TextField(verbose_name='Նկարագրություն')),
                ('confidence_level', models.CharField(choices=[('low', 'Ցածր'), ('medium', 'Միջին'), ('high', 'Բարձր')], default='medium', max_length=20, verbose_name='Վստահության մակարդակ')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Հայտնաբերում')),
                ('source_feed', models.CharField(blank=True, max_length=100, verbose_name='Աղբյուրի feed')),
            ],
            options={
                'verbose_name': 'Կիբեռ հետախուզություն',
                'verbose_name_plural': 'Կիբեռ հետախուզություն',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='threat',
            options={'ordering': ['-reported_at'], 'verbose_name': 'Սպառնալիք', 'verbose_name_plural': 'Սպառնալիքներ'},
        ),
        migrations.AddField(
            model_name='threat',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP հասցե'),
        ),
        migrations.AddField(
            model_name='threat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ակտիվ է'),
        ),
        migrations.AddField(
            model_name='threat',
            name='severity',
            field=models.CharField(choices=[('low', 'Ցածր'), ('medium', 'Միջին'), ('high', 'Բարձր'), ('critical', 'Կրիտիկական')], default='medium', max_length=10, verbose_name='Լուրջություն'),
        ),
        migrations.AddField(
            model_name='threat',
            name='target_country',
            field=models.CharField(default='Armenia', max_length=100, verbose_name='Թիրախային երկիր'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='type',
            field=models.CharField(choices=[('phishing', 'Ֆիշինգ'), ('malware', 'Վնասակար ծրագիր'), ('ddos', 'DDoS հարձակում'), ('data_breach', 'Տվյալների արտահոսք'), ('ransomware', 'Ransomware'), ('other', 'Այլ')], max_length=20, verbose_name='Տեսակ'),
        ),
        migrations.CreateModel(
            name='PhishingURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('category', models.CharField(max_length=20, verbose_name='Կատեգորիա')),
                ('platform_source', models.CharField(blank=True, max_length=200, verbose_name='Հարթակ/Աղբյուր')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ է')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Վերջին ստուգում')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծված')),
                ('source_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.phishingreport', verbose_name='Նախնական զեկուցում')),
            ],
            options={
                'verbose_name': 'Ֆիշինգ URL',
                'verbose_name_plural': 'Ֆիշինգ URL-ներ',
                'ordering': ['-created_at'],
                'unique_together': {('url', 'source_report')},
            },
        ),
    ]
