# Generated by Django 5.2.4 on 2025-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('banking', 'Բանկային'), ('social_media', 'Սոցիալական ցանցեր'), ('sms', 'SMS'), ('other', 'Այլ')], max_length=20, verbose_name='Կատեգորիա')),
                ('description', models.TextField(verbose_name='Նկարագրություն')),
                ('suspicious_url', models.CharField(blank=True, max_length=500, verbose_name='Կասկածելի URL')),
                ('suspicious_email', models.CharField(blank=True, max_length=200, verbose_name='Կասկածելի էլ. փոստ')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='Հետադարձ կապի տվյալներ')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Անանուն')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծված')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Կարգավիճակ')),
            ],
            options={
                'verbose_name': 'Ֆիշինգի զեկուցում',
                'verbose_name_plural': 'Ֆիշինգի զեկուցումներ',
            },
        ),
    ]
