# Generated by Django 5.2.4 on 2025-07-23 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ամսաթիվ')),
                ('total_reports', models.IntegerField(default=0, verbose_name='Ընդհանուր զեկուցումներ')),
                ('resolved_reports', models.IntegerField(default=0, verbose_name='Լուծված զեկուցումներ')),
                ('pending_reports', models.IntegerField(default=0, verbose_name='Ընթացքի մեջ')),
            ],
            options={
                'verbose_name': 'Զեկուցման վիճակագրություն',
                'verbose_name_plural': 'Զեկուցումների վիճակագրություն',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Կոնտակտային տեղեկություն', 'verbose_name_plural': 'Կոնտակտային տեղեկություններ'},
        ),
        migrations.AlterModelOptions(
            name='phishingreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ֆիշինգի զեկուցում', 'verbose_name_plural': 'Ֆիշինգի զեկուցումներ'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ստեղծված'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ակտիվ'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Արտակարգ իրավիճակի համար'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Հերթականություն'),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Ադմինի գրառումներ'),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Ցածր'), ('medium', 'Միջին'), ('high', 'Բարձր'), ('critical', 'Կրիտիկական')], default='medium', max_length=10, verbose_name='Լուրջություն'),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Թարմացված'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Նկարագրություն'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Էլ. փոստ'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Հեռախոս'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Կայք'),
        ),
        migrations.AlterField(
            model_name='phishingreport',
            name='category',
            field=models.CharField(choices=[('banking', 'Բանկային ֆիշինգ'), ('social_media', 'Սոցիալական ցանցեր'), ('sms', 'SMS ֆիշինգ'), ('email', 'Էլ. փոստի ֆիշինգ'), ('cryptocurrency', 'Կրիպտոարժույթ'), ('online_shopping', 'Առցանց գնումներ'), ('government', 'Պետական ծառայություններ'), ('other', 'Այլ')], max_length=20, verbose_name='Կատեգորիա'),
        ),
        migrations.AlterField(
            model_name='phishingreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Դիտարկման տակ'), ('investigating', 'Քննվում է'), ('resolved', 'Լուծված'), ('closed', 'Փակված'), ('false_positive', 'Կեղծ ահազանգ')], default='pending', max_length=20, verbose_name='Կարգավիճակ'),
        ),
    ]
