# Generated by Django 5.2.4 on 2025-07-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_reportstatistics_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingreport',
            name='platform_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Հարթակ/Աղբյուր'),
        ),
        migrations.CreateModel(
            name='ContactGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_to_contact', models.TextField(verbose_name='Երբ դիմել')),
                ('required_documents', models.TextField(blank=True, verbose_name='Անհրաժեշտ փաստաթղթեր')),
                ('process_description', models.TextField(blank=True, verbose_name='Գործընթացի նկարագրություն')),
                ('response_time', models.CharField(blank=True, max_length=100, verbose_name='Պատասխանի ժամկետ')),
                ('additional_info', models.TextField(blank=True, verbose_name='Լրացուցիչ տեղեկություններ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծված')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Թարմացված')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guideline', to='reporting.contactinfo', verbose_name='Կոնտակտ')),
            ],
            options={
                'verbose_name': 'Կոնտակտի ուղեցույց',
                'verbose_name_plural': 'Կոնտակտների ուղեցույցներ',
            },
        ),
    ]
