# Generated by Django 5.2.4 on 2025-07-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_phishingreport_platform_source_contactguideline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingreport',
            name='platform_source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('email', 'Էլ. փոստ'), ('sms', 'SMS'), ('website', 'Կայքէջ'), ('other', 'Այլ')], max_length=200, verbose_name='Հարթակ/Աղբյուր'),
        ),
    ]
