# Generated by Django 5.2.4 on 2025-07-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_alter_phishingreport_platform_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingreport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Նկարագրություն'),
        ),
    ]
