# Generated by Django 5.2.4 on 2025-07-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_alter_phishingreport_description'),
    ]

    operations = [
        # Step 1: Create PlatformSource model
        migrations.CreateModel(
            name='PlatformSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Հարթակ/Աղբյուր')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ')),
            ],
            options={
                'verbose_name': 'Հարթակ/Աղբյուր',
                'verbose_name_plural': 'Հարթակներ/Աղբյուրներ',
                'ordering': ['name'],
            },
        ),
    ]
