# Generated by Django 5.2.4 on 2025-07-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20250727_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishingreport',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='platform_source_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='Այլ հարթակ/աղբյուր'),
        ),
        migrations.AlterField(
            model_name='phishingreport',
            name='platform_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.platformsource', verbose_name='Հարթակ/Աղբյուր'),
        ),
    ]
