# Generated by Django 5.2.4 on 2025-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_remove_phishingreport_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingreport',
            name='damage_details',
            field=models.TextField(blank=True, verbose_name='Վնասի մանրամասներ'),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('data_breach', 'Տվյալների արտահոսք/գաղտնիության խախտում'), ('personal_data_leak', '└ Անձնական տվյալների արտահոսք'), ('login_data_theft', '└ Մուտքի տվյալների գողություն'), ('banking_data_leak', '└ Բանկային տվյալների արտահոսք'), ('sensitive_data_leak', '└ Առաջադեմ անձնական տվյալների արտահոսք'), ('official_data_leak', '└ Պետական/պաշտոնական տվյալների արտահոսք'), ('data_loss', '└ Տվյալների կորուստ/ոչնչացում'), ('privacy_violation', '└ Անհատական գաղտնիության խախտում'), ('financial_loss', 'Ֆինանսական կորուստներ'), ('unauthorized_withdrawal', '└ Չարտոնված գումարի հանում'), ('unauthorized_payments', '└ Չարտոնված վճարումներ/փոխանցումներ'), ('service_abuse', '└ Վճարովի ծառայությունների չարաշահում'), ('financial_fraud', '└ Ֆինանսական տվյալների կեղծում'), ('loan_abuse', '└ Վարկերի չարաշահում իմ անունով'), ('unknown_charges', '└ Անհայտ վճարումներ/գումարների անհետացում'), ('account_loss', 'Օգտահաշվի կորուստ/չարաշահում'), ('account_access_loss', '└ Օգտահաշվի մուտքի կորուստ'), ('message_privacy_breach', '└ Անձնական հաղորդագրությունների գաղտնիության խախտում'), ('account_misuse', '└ Օգտահաշվի չարամիտ օգտագործում'), ('account_fraud', '└ Օգտահաշվի միջոցով խարդախություն'), ('multi_account_breach', '└ Բազմաթիվ ծառայությունների անվտանգության խաթարում'), ('device_control_loss', 'Սարքի/համակարգի վերահսկողության կորուստ'), ('malware_installation', '└ Չարամիտ ծրագրի տեղադրում'), ('unauthorized_remote_access', '└ Չարտոնված հեռակա մուտք'), ('data_destruction', '└ Տվյալների ոչնչացում/փոխում'), ('ransomware_attack', '└ Տվյալների գաղտնագրում (ransomware)'), ('device_theft', '└ Սարքի կորուստ/գողություն'), ('psychological_damage', 'Հոգեբանական/սոցիալական վնասներ'), ('psychological_pressure', '└ Հոգեբանական ճնշում/շանտաժ'), ('cyberbullying', '└ Կիբեռբուլլինգ/վիրավորանք'), ('reputation_damage', '└ Համբավի վնասում/վարկաբեկում'), ('fake_account_creation', '└ Կեղծ հաշվի ստեղծում իմ անունով'), ('social_family_problems', '└ Սոցիալական/ընտանեկան խնդիրներ'), ('incident_no_damage', 'Դեպք եղել է, բայց վնաս չկա'), ('clicked_suspicious_link', '└ Սեղմել եմ կասկածելի հղման վրա, վնաս չկա'), ('opened_suspicious_email', '└ Բացել եմ կասկածելի նամակ'), ('provided_data_no_damage', '└ Տվյալ եմ տրամադրել, վնաս չկա'), ('prevented_damage', '└ Կանխատեսել եմ ռիսկը, առանց հետևանքների'), ('other_damage', 'Այլ վնասներ'), ('other_specify', '└ Այլ (խնդրում եմ մանրամասնել)')], max_length=50, verbose_name='Կրած վնասի տեսակը'),
        ),
    ]
