# Generated by Django 5.2.4 on 2025-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_phishingreport_damage_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Վնասի տեսակ')),
                ('category', models.CharField(choices=[('data_breach', 'Տվյալների արտահոսք/գաղտնիության խախտում'), ('financial_loss', 'Ֆինանսական կորուստներ'), ('account_loss', 'Օգտահաշվի կորուստ/չարաշահում'), ('device_control_loss', 'Սարքի/համակարգի վերահսկողության կորուստ'), ('psychological_damage', 'Հոգեբանական/սոցիալական վնասներ'), ('incident_no_damage', 'Դեպք եղել է, բայց վնաս չկա'), ('other_damage', 'Այլ վնասներ')], max_length=50, verbose_name='Կատեգորիա')),
                ('description', models.TextField(blank=True, verbose_name='Նկարագրություն')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ')),
                ('order', models.IntegerField(default=0, verbose_name='Հերթականություն')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծված')),
            ],
            options={
                'verbose_name': 'Վնասի տեսակ',
                'verbose_name_plural': 'Վնասի տեսակներ',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='phishingreport',
            name='damage_type',
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='has_damage',
            field=models.BooleanField(default=False, verbose_name='Արդյոք կրել եք վնաս այս դեպքի արդյունքում?'),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='damage_types',
            field=models.ManyToManyField(blank=True, to='reporting.damagetype', verbose_name='Կրած վնասի տեսակները'),
        ),
    ]
