# Generated by Django 5.2.4 on 2025-07-27 14:24

import apps.reporting.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_damagetype_remove_phishingreport_damage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingreport',
            name='evidence_audio',
            field=models.FileField(blank=True, help_text='Թույլատրելի ֆորմատներ: MP3, WAV, OGG, M4A, AAC (մաքս. 15ՄԲ)', null=True, upload_to=apps.reporting.models.evidence_upload_path, validators=[apps.reporting.models.validate_audio_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'aac'])], verbose_name='Ապացույցի ձայնագրություն (մաքս. 15ՄԲ)'),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='evidence_document',
            field=models.FileField(blank=True, help_text='Թույլատրելի ֆորմատներ: PDF, DOC, DOCX, TXT, RTF (մաքս. 10ՄԲ)', null=True, upload_to=apps.reporting.models.evidence_upload_path, validators=[apps.reporting.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf'])], verbose_name='Ապացույցի փաստաթուղթ (մաքս. 10ՄԲ)'),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='evidence_image',
            field=models.ImageField(blank=True, help_text='Թույլատրելի ֆորմատներ: JPG, PNG, GIF, WebP (մաքս. 5ՄԲ)', null=True, upload_to=apps.reporting.models.evidence_upload_path, validators=[apps.reporting.models.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Ապացույցի նկար (մաքս. 5ՄԲ)'),
        ),
    ]
