# Generated by Django 5.2.4 on 2025-07-27 15:11

import apps.reporting.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_phishingreport_evidence_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingreport',
            name='evidence_files',
            field=models.FileField(blank=True, help_text='Թույլատրվում են՝ նկարներ (մաքս. 5ՄԲ), փաստաթղթեր (մաքս. 10ՄԲ), վիդեո (մաքս. 50ՄԲ), ձայն (մաքս. 15ՄԲ), արխիվ (մաքս. 25ՄԲ). Ընդհանուր մաքս. ծավալ՝ 100ՄԲ', null=True, upload_to=apps.reporting.models.evidence_upload_path, validators=[apps.reporting.models.validate_any_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'tiff', 'pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv', 'mp3', 'wav', 'ogg', 'm4a', 'aac', 'flac', 'zip', 'rar', '7z'])], verbose_name='Կցել ֆայլ'),
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.reporting.models.evidence_upload_path, validators=[apps.reporting.models.validate_any_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'tiff', 'pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv', 'mp3', 'wav', 'ogg', 'm4a', 'aac', 'flac', 'zip', 'rar', '7z'])])),
                ('file_type', models.CharField(choices=[('image', 'Նկար'), ('document', 'Փաստաթուղթ'), ('video', 'Վիդեո'), ('audio', 'Ձայն'), ('archive', 'Արխիվ'), ('other', 'Այլ')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Նկարագրություն')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('phishing_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='reporting.phishingreport')),
            ],
            options={
                'verbose_name': 'Ապացույցի ֆայլ',
                'verbose_name_plural': 'Ապացույցի ֆայլեր',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
