# Generated by Django 5.2.4 on 2025-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Անուն')),
                ('character_type', models.CharField(choices=[('ara', 'Արա Գեղեցիկ'), ('shamiram', 'Շամիրամ')], max_length=20, verbose_name='Կերպարի տեսակ')),
                ('description', models.TextField(verbose_name='Նկարագրություն')),
                ('image', models.ImageField(upload_to='characters/', verbose_name='Նկար')),
                ('is_positive', models.BooleanField(default=True, verbose_name='Դրական կերպար')),
            ],
            options={
                'verbose_name': 'Կերպար',
                'verbose_name_plural': 'Կերպարներ',
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reports', models.IntegerField(default=0, verbose_name='Ընդհանուր զեկուցումներ')),
                ('monthly_reports', models.IntegerField(default=0, verbose_name='Ամսվա զեկուցումներ')),
                ('total_quizzes', models.IntegerField(default=0, verbose_name='Ընդհանուր քուիզներ')),
                ('total_url_checks', models.IntegerField(default=0, verbose_name='URL ստուգումներ')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Վերջին թարմացում')),
            ],
            options={
                'verbose_name': 'Կայքի վիճակագրություն',
                'verbose_name_plural': 'Կայքի վիճակագրություններ',
            },
        ),
    ]
