# Generated by Django 5.2.4 on 2025-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Գաղտնիության քաղաքականություն', max_length=200, verbose_name='Վերնագիր')),
                ('content', models.TextField(help_text='Գաղտնիության քաղաքականության ամբողջական տեքստը', verbose_name='Բովանդակություն')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Վերջին թարմացում')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծված')),
            ],
            options={
                'verbose_name': 'Գաղտնիության քաղաքականություն',
                'verbose_name_plural': 'Գաղտնիության քաղաքականություններ',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ծառայության պայմաններ', max_length=200, verbose_name='Վերնագիր')),
                ('content', models.TextField(help_text='Ծառայության պայմանների ամբողջական տեքստը', verbose_name='Բովանդակություն')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Վերջին թարմացում')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծված')),
            ],
            options={
                'verbose_name': 'Ծառայության պայմաններ',
                'verbose_name_plural': 'Ծառայության պայմանների փաստաթղթեր',
                'ordering': ['-last_updated'],
            },
        ),
    ]
