# Generated by Django 5.2.4 on 2025-07-19 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Հարցի տեքստ')),
                ('question_type', models.CharField(choices=[('phishing_detection', 'Ֆիշինգ է թե ոչ'), ('educational', 'Ուսուցողական'), ('millionaire', 'Միլիոնատեր')], max_length=20, verbose_name='Հարցի տեսակ')),
                ('difficulty', models.CharField(choices=[('easy', 'Հեշտ'), ('medium', 'Միջին'), ('hard', 'Դժվար')], default='medium', max_length=10, verbose_name='Բարդություն')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Նկար')),
                ('explanation', models.TextField(blank=True, verbose_name='Բացատրություն')),
                ('points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Միավորներ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծված')),
            ],
            options={
                'verbose_name': 'Հարց',
                'verbose_name_plural': 'Հարցեր',
                'ordering': ['question_type', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Անվանում')),
                ('category_type', models.CharField(choices=[('school', 'Դպրոցական'), ('student', 'Ուսանող'), ('professional', 'Մասնագիտական')], max_length=20, verbose_name='Կատեգորիա')),
                ('professional_field', models.CharField(blank=True, choices=[('government', 'Պետական'), ('banking', 'Բանկային/Ֆինանսներ'), ('education', 'Կրթություն'), ('healthcare', 'Առողջապահություն'), ('it', 'Տեղեկատվական տեխնոլոգիաներ'), ('other', 'Այլ')], max_length=20, null=True, verbose_name='Մասնագիտական ոլորտ')),
                ('description', models.TextField(blank=True, verbose_name='Նկարագրություն')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ')),
            ],
            options={
                'verbose_name': 'Քուիզի կատեգորիա',
                'verbose_name_plural': 'Քուիզի կատեգորիաներ',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200, verbose_name='Պատասխանի տեքստ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Ճիշտ պատասխան')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Հարց')),
            ],
            options={
                'verbose_name': 'Պատասխան',
                'verbose_name_plural': 'Պատասխաններ',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcategory', verbose_name='Կատեգորիա'),
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Սեսիայի բանալի')),
                ('question_type', models.CharField(choices=[('phishing_detection', 'Ֆիշինգ է թե ոչ'), ('educational', 'Ուսուցողական'), ('millionaire', 'Միլիոնատեր')], max_length=20, verbose_name='Հարցի տեսակ')),
                ('current_question', models.IntegerField(default=0, verbose_name='Ընթացիկ հարց')),
                ('total_questions', models.IntegerField(default=10, verbose_name='Ընդհանուր հարցեր')),
                ('score', models.IntegerField(default=0, verbose_name='Միավորներ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Ավարտված')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Սկսվել է')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ավարտվել է')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcategory', verbose_name='Կատեգորիա')),
            ],
            options={
                'verbose_name': 'Քուիզի սեսիա',
                'verbose_name_plural': 'Քուիզի սեսիաներ',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(verbose_name='Վերջնական միավոր')),
                ('percentage', models.FloatField(verbose_name='Տոկոսային արդյունք')),
                ('character_result', models.CharField(choices=[('ara', 'Արա Գեղեցիկ'), ('shamiram', 'Շամիրամ')], max_length=20, verbose_name='Կերպարային արդյունք')),
                ('feedback_message', models.TextField(verbose_name='Արձագանքի հաղորդագրություն')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizsession', verbose_name='Սեսիա')),
            ],
            options={
                'verbose_name': 'Քուիզի արդյունք',
                'verbose_name_plural': 'Քուիզի արդյունքներ',
            },
        ),
    ]
