# Generated by Django 5.2.4 on 2025-07-20 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.answer'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='session',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizsession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizcategory'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('classic', 'Ուսուցողական Քուիզ'), ('millionaire', 'Միլիոնատեր')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='category_type',
            field=models.CharField(choices=[('school', 'Դպրոցական'), ('student', 'Ուսանող'), ('professional', 'Մասնագիտական')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='professional_field',
            field=models.CharField(blank=True, choices=[('gov', 'Պետական'), ('bank', 'Բանկային'), ('edu', 'Կրթական'), ('it', 'IT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='character_result',
            field=models.CharField(choices=[('ara', 'Արա Գեղեցիկ'), ('shamiram', 'Շամիրամ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='feedback_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='final_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizsession'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quizcategory'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='question_type',
            field=models.CharField(choices=[('classic', 'Ուսուցողական Քուիզ'), ('millionaire', 'Միլիոնատեր')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='session_key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
