# Generated by Django 5.2.4 on 2025-07-23 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-percentage', '-final_score', '-created_at']},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
