# Generated by Django 5.2.4 on 2025-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=500, verbose_name='URL կամ Էլ. փոստ')),
                ('status', models.CharField(choices=[('safe', 'Անվտանգ'), ('suspicious', 'Կասկածելի'), ('malicious', 'Վտանգավոր'), ('pending', 'Սպասում է ձեռքով մշակման')], default='pending', max_length=20, verbose_name='Կարգավիճակ')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Աղբյուր')),
                ('analysis_result', models.TextField(blank=True, verbose_name='Վերլուծության արդյունք')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստուգման ժամանակ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Թարմացման ժամանակ')),
            ],
            options={
                'verbose_name': 'URL ստուգում',
                'verbose_name_plural': 'URL ստուգումներ',
            },
        ),
    ]
