# Generated by Django 5.2.4 on 2025-07-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virustotal_result', models.JSONField(blank=True, null=True, verbose_name='VirusTotal արդյունք')),
                ('kaspersky_result', models.JSONField(blank=True, null=True, verbose_name='Kaspersky արդյունք')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստուգման ժամանակ')),
                ('url_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='url_checker.urlcheck')),
            ],
            options={
                'verbose_name': 'URL ստուգման արդյունք',
                'verbose_name_plural': 'URL ստուգման արդյունքներ',
            },
        ),
    ]
