# Generated by Django 5.2.4 on 2025-07-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_checker', '0004_urlcheckresult_safebrowsing_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcheck',
            name='input_text',
            field=models.TextField(verbose_name='URL կամ Էլ. փոստ'),
        ),
    ]
