# Generated by Django 5.2.4 on 2025-07-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_email_analyzer', '0002_urlcheckresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Աղբյուրի անուն')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (for code)')),
                ('api_url', models.URLField(blank=True, verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('api_headers', models.JSONField(blank=True, default=dict, verbose_name='Additional Headers')),
                ('display_name', models.CharField(max_length=100, verbose_name='Ցուցադրվող անուն')),
                ('description', models.CharField(max_length=200, verbose_name='Նկարագրություն')),
                ('icon_class', models.CharField(default='fas fa-shield-alt', max_length=100, verbose_name='Icon Class (FontAwesome)')),
                ('color_class', models.CharField(default='text-primary', max_length=50, verbose_name='Color Class')),
                ('status', models.CharField(choices=[('active', 'Ակտիվ'), ('inactive', 'Ոչ ակտիվ'), ('maintenance', 'Սպասարկում'), ('coming_soon', 'Շուտով հասանելի')], default='coming_soon', max_length=20, verbose_name='Կարգավիճակ')),
                ('integration_type', models.CharField(choices=[('url_scanner', 'URL Scanner'), ('ip_checker', 'IP Checker'), ('file_scanner', 'File Scanner'), ('domain_reputation', 'Domain Reputation')], default='url_scanner', max_length=30, verbose_name='Ինտեգրացիայի տեսակ')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Դասակարգման հերթականություն')),
                ('priority', models.PositiveIntegerField(default=50, verbose_name='Առաջնություն (1-100)')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, verbose_name='Հարցումներ րոպեում')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='Timeout (վայրկյան)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Անվտանգության Ինտեգրացիա',
                'verbose_name_plural': 'Անվտանգության Ինտեգրացիաներ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('safe', 'Անվտանգ'), ('malicious', 'Վտանգավոր'), ('suspicious', 'Կասկածելի'), ('pending', 'Սպասում'), ('error', 'Սխալ')], max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'Բարձր'), ('medium', 'Միջին'), ('low', 'Ցածր')], default='medium', max_length=10)),
                ('raw_response', models.JSONField(default=dict, verbose_name='Raw API Response')),
                ('processed_data', models.JSONField(default=dict, verbose_name='Processed Data')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_results', to='url_email_analyzer.urlcheck')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_email_analyzer.securityintegration')),
            ],
            options={
                'verbose_name': 'Ինտեգրացիայի արդյունք',
                'verbose_name_plural': 'Ինտեգրացիայի արդյունքներ',
                'unique_together': {('integration', 'url_check')},
            },
        ),
    ]
